server:
  port: 28001
powerfactor:
  exportdatasize: 1000
##版本号
version: /v1

#脱敏配置
encrypt.enable: true
#导出配置
fileExport.auth.switch: true
integrate: N

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    # hiddenmethod:
    #   filter:
    #     enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true #当出现404错误时,是否直接抛出异常
    async:
      request-timeout: 120000
  # cloud.nacos.discovery:
  #   ip: 10.12.7.159
  #   port: 31620
  resources:
    add-mappings: false #是否开启默认的资源处理
  #  redis:
  #    expiration: 3600 #设置缓存到期时间,单位秒
  #    password: foo
  #    database: 1
  #    timeout: 100000 #客户端超时时间：单位是毫秒
  #    pool:
  #      max-active: 50 #最大连接数：能够同时建立的“最大链接个数”
  #      max-idle: 20 #最大空闲数：空闲链接数大于maxIdle时，将进行回收
  #      min-idle: 5 #最小空闲数
  #      max-wait: 1000 #最大等待时间：单位ms
  #    #单节点方式
  #    host: 10.12.70.61:6379
  #    port: 6379
  http:
    multipart:
      max-file-size: 80MB
      max-request-size: 80MB
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

management:
  security:
    enabled: false

feign:
  hystrix:
    enabled: true





exportScadaImage:
  path: E:\test

drillKnowledgeUploadPath: /tmp/

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 800000

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
    com.migu.tsg.microservice.atomicservice.composite.controller: debug #输出rbac-service日志
    #tk.mybatis.mapper.common.base.select: debug #输出mybatis select SQL
    #tk.mybatis.mapper.common.base.update: debug #输出mybatis update SQL
    #tk.mybatis.mapper.common.base.insert: debug #输出mybatis insert SQL
    #tk.mybatis.mapper.common.base.delete: debug #输出mybatis delete SQL
  file: ./composite.log ##日志文件,绝对路径或相对路径

log:
  hosts: 172.30.150.26:29200
  userName: 123
  password: 456
  needAuth: true
  maxTotalConnectionPerRoute: 1
  maxTotalConnection: 10
  multiThreaded: true
  readTimeout: 200000

ribbon:
  ReadTimeout: 1200000
  ConnectTimeout: 1200000

path: /temp/
ftpIP: 10.1.122.36
ftpPort: 21
ftpUser: user
ftpPwd: 123

composite:
  yamlUrl: http://172.30.150.30:18888/ms-sso-dev.yml


ftp:
  host: 10.1.4.113
  host62: 10.1.4.113  #10.1.5.143
  password62: "wccQKPbCmx8@r*6p"
  port: 21
  username: vsftpd
  password: "wccQKPbCmx8@r*6p"
  uploadpath: /tmp/electricdrawing/upload/


nginx:
  host: 10.1.203.121
  port: 8899
sso:
  url: http://10.243.67.75:3375/index/park?entryparams=
  sso_password: admin&nics,ECCR!2#4&nics,zhuowang

aspire.webbas.component.safeguarding:
  illegalityParam:  <,>,</script,<script,script[\s],<img,%27,and[\s],select[\s],insert[\s],exec[\s],update[\s],drop[\s],truncate[\s],declare[\s],count[\(],decode[\s],<script.*>.*<\/script\s*>,document\s*.\s*cookie,document\s*.\s*write,ascii\s*\(.*\),chr\s*\(.*\),alter\s+,create\s+,dbms_pipe\s*.\s*receive_message,truncate\s+,drop\s+,insert\s+,update\s+,delete\s+,select\s+,execute\s+,waitfor\s+,grant\s+,lock\s+table\s+,cast\s*\(.*\),str\s*\(.*\),convert\s*\(.*\),floor\s*\(.*\),upper\s*\(.*\),lower\s*\(.*\),sleep\s*\(.*\),pg_sleep\s*\(.*\),union\s+all\s+,order\s+by\s+,group\s+by\s+,case\s+when\s+,waitfor\s+delay\s+,from\s+information_schema\s*,limit\s+\d\s*,extractvalue\s*\(.*\),concat\s*\(.*\),md5\s*\(.*\)
  availableSuffixes: doc,docx,xls,xlsx,ppt,pptx,pdf,txt,rar,zip,mp4,jpg,jpeg,gif,png
  whiteList:  #白名单，List集合
  - /v1/bulletin/saveSendNotice
  - /v1/scada/saveScadaCanvas/**
  - /v1/alerts/createColumnInfo**
  - /xxl-static/**
  - /xxl/**
  
#是否省省平台，0为不是，1为是
isProvincePlat: 0
#杭研的数据统计接口url
cmccAnalyticsServerUrl: "http://120.79.221.0:86/analyzer/api/"
#杭研的数据统计接口appSecret
cmccAnalyticsAppSecret: "dxefIupji3m68MLvC4xrNIuQPvSRmThrpxa5PS9NEXMqKHrDdgCdY2Zjq93v7pVlXybO5tJYmE0="
#是否发送杭研统计数据 1为发送 0为不发送
cmccAnalyticsIsSend: 1
#杭研的数据统计定时发送间隔，单位是毫秒，不配置的话默认是10秒
cmccAnalyticsCron: 10000

#oa_sso: N
#unportal.client.user.enable: true
#unportal.host: 10.12.70.60
#unportal.client_id: 11111
#unportal.client_key: 222222
oa_sso: Y
unportal.client.user.enable: true
unportal.host: 10.1.203.38:38392
unportal.client_id: spider
unportal.client_key: $2a$10$M.vmJuHDHuA3Y65.1Mje9OXiUBMOIcus6JEb9lSoKeu70b2ZIqhlG

nginxAuth.refererIp: 10.1.203.121
auth.str: 01-01
auth.provinceFlag: province-energy
# spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration

#账号同步推送开关
rbacAccount:
  enablePushBpm: true
  enablePushOA: true

tokenInterceptor:
  validAuthorization:
    enable: false
    excludeUrl: queryListByKeycloak,user/update/keycloak,log/saveEventLog,ldap/validCodeImage,ldap/checkValidCode,monitorapi/nginxAuth,user/encrypt,configManagement/selectSysVersion
#     nonRepeatSubmit:
#       enable: true
#       filter: add,update,download,upload


# 统一单点登录
loginsso:
  isDev: false
  #动环统一url
  redirectUrl: http://10.1.203.120:9080/spider/web/v1/login/sso
  #webbas内置url
  webbasSSOUrl: http://10.1.203.120:9080/spider/web/web/auth/v1/sso/verify?loginType=2&domain=admin&username=%s&token=%s&redirectUrl=%s
  #pc端成功错误跳转url
  PCFrontSuccessUrl: http://10.1.203.120:9080/spider/web/login-app/sso?sso=1&username=%s&domain=admin&ssoType=1
  PCFrontFailUrl: http://10.1.203.120:9080/spider/web/
  #MOA成功错误跳转地址
  MOAFrontSuccessUrl: http://10.1.203.120:9080/prodenv/spider/inop/h5?sso=1&username=%s&domain=admin&ssoType=1
  MOAFrontFailUrl: http://10.1.203.120:9080/prodenv/spider/inop/h5?sso=1&username=%s&domain=admin&ssoType=1
alertEventListener:
  VisibleAlertEventListner:
    switch: true

# fsu管理-配置管理-机房设备信息维护，是否开启设备编码一致性校验
enable-device-code-unify-check: true

sqlInjection.urlBlackList: /v1/syslog,/v1/report/operationlog


