jasypt:
    encryptor:
        password: 15d680c2d2be4dba8f
        algorithm: PBEWithMD5AndDES
        iv-generator-classname: org.jasypt.iv.NoIvGenerator
spring.main.allow-bean-definition-overriding: true
spring.main.allow-circular-references: true

spring.servlet.multipart.max-file-size: 100MB
spring.servlet.multipart.max-request-size: 1000MB
spring.liquibase.enabled: false
server:
  port: 18085
flowable:
    database-schema-update: false
    async-executor-activate: false

com.aspire.zypt:
    version: v1
    sdm:
        business:
            tenantId: 1 #系统租户ID
            domainId:  #业务域ID（默认）
        engine:
            contextPath: /web/zypt #请求路径前缀
        result:
            detailMessage.open: false  #是否输出详细信息结果 默认false
init.param.tempFilePath: D:/tmp

caffeine.spec: maximumSize=1000,expireAfterAccess=600s
id.type: snow
#数据库配置
spring.datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.203.120:3306/sc-spider?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: GPGAErA%ZkhMk59*jaD
    dbType: mysql #postgres # mysql
    hikari:
        #连接超时时间：毫秒，小于250毫秒，否则被重置为默认值30秒
        connection-timeout: 20000
        #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
        minimum-idle: 5
        #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
        maximum-pool-size: 20
        #空闲连接最大存活时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
        idle-timeout: 600000
        #连接池返回的连接默认自动提交，默认只 true
        auto-commit: true
        # 连接最大存活时间，不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
        max-lifetime: 1800000
        #用于测试连接是否可用的查询语句
        connection-test-query: select 1