server:
  port: 28011

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: true
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true


ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 60000


mybatis:
  mapperLocations:
    - classpath*:sqlmap/*Mapper.xml
  type-aliases-package:
    org.springboot.sample.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true