mybatis:
  mapperLocations:
    - classpath*:sqlmap/*Mapper.xml
  type-aliases-package: 
     org.springboot.sample.entity
#  configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#     map-underscore-to-camel-case: true

code:
  instruct:
    codingList:
      - "{\"name\":\"ZNDBDY\",\"type\":\"9,6\",\"code\":\"009301,009302,009303,006309\"}"
      - "{\"name\":\"ZNDBDL\",\"type\":\"92\",\"code\":\"092324\"}"
      - "{\"name\":\"DYPDGSRDY\",\"type\":\"2\",\"code\":\"002303,002310,002317\"}"
      - "{\"name\":\"JLSRDY\",\"type\":\"6\",\"code\":\"006301,006302,006303\"}"
      - "{\"name\":\"DCZDY\",\"type\":\"6\",\"code\":\"006218\"}"
      - "{\"name\":\"ZFZDL\",\"type\":\"6\",\"code\":\"006309\"}"
      - "{\"name\":\"ZLQSCDY\",\"type\":\"6\",\"code\":\"006218\"}"
      - "{\"name\":\"ZLSCDY\",\"type\":\"6\",\"code\":\"006308\"}"
      - "{\"name\":\"ZDY1\",\"type\":\"7,68\",\"code\":\"007302,068301\"}"
      - "{\"name\":\"ZDY2\",\"type\":\"7,68\",\"code\":\"007302,068301\"}"
      - "{\"name\":\"HFWD\",\"type\":\"11,12,15\",\"code\":\"011301,012301,015203\"}"
      - "{\"name\":\"JZWD\",\"type\":\"17\",\"code\":\"017301\"}"
      - "{\"name\":\"YJZT\",\"type\":\"5\",\"code\":\"005401\"}"

app:
  omc:
    enableSftp: true
    listenPort: 31232       #tcp监听端口
    powerCutAlertCode: "006031,002010,092001,006038" #停电告警编码
    powerCutAlertSiteType: 3,4 #只监听通信基站和传输节点的停电告警
    autoIncrementOffset: 70
    omsPushProvince: 01-01
    checkDevice:
      enableExecutor: true  #是否启用独立线程池，控制并发量，防止外部调用拖垮omc服务，默认true
      executorPoolSize: 2  #线程池大小
collectTask:
  collectRate: 300 #采集频率(秒）,默认5分钟
  cjkReadCacheValueDelay: 60 #C接口设备读取缓存值的延迟时间（秒）,默认60s
  passTimeOnAlertEnd: 5 #60 #告警消除后任务继续执行的时长（分钟）,默认1小时
  maxRunTimeOnAlertStart: 10 #10080 #任务的最长执行时间（分钟），默认7天（一周）


# logging:
#   level:
#     com.aspire.gemc.omc: debug