server:
  port: 8486

hidden:
  danger:
    dwd:
      #配置数据归属省份
      precinctId: 01-24
      #触发fsu到dwd隐患定时任务
      cron: 0 0 4 * * ?
      #fsu到dwd对应测点
      meteCodes: "001304,001305,001306,001307,001308,001309,001311,001312,001313,001320,001321,001322,001325,002302,002303,002304,002307,002309,002310,002311,002314,002316,002317,002318,002321,004301,004302,004304,009301,009302,009303,009304,009305,009306,009307,009308,009309,009310,009313,088301,088302,088306,088307,092304,092305,092306"
    dws:
      #三相电流隐患分析测点
      meteCodes: "001307,001308,001309,002302,002309,002316,092304,092305,092306"
      #dwd到dws三相电流隐患分析定时任务
      cron: 0 0 9 * * ?
    capacity:
      #配电容量负载率门限
      threshold: 20
  convert:
    device:
      cron: 0 0 0 * * ?
capacity:
  warning:
    #配电容量dwd->dws定时任务
    cron: 0 0 17 * * ?
    #配置稽核上送N天前的数据，默认1天
    dayN: 2
    
#超期服役相关配置
overdue:
  percent: 70  #超期服役警示阈值
  multiple: 1.5  #超期服役倍数
  cron: 0 0 18 * * ?  #后台定时任务
  alertMonthBetween: 2  #统计告警月份个数(这里的1代表上个月,2代表上两个月)
  meteCodes:
    #UPS设备
    ups: "008020,008021,008030,008034,008040,008044,008045,008046,008047,008052,008053,008054" 
    #变压器
    transform: "003002,003006,003001,003004,003005"  #测试用003001	
    #高压配电
    highDistribution: "001034,001038,001040"
    #高压直流开关电源
    highPower: "087002,087012,087031,087040,087043"
    #高压直流配电
    highDcDistribution: "088003"
    #低压交流配电
    lowAcDistribution: "002022,002023,002034,002035,002013,004003"
    #发电机组
    powerGeneration: "005001,005015,005022,005049"
    #开关电源
    switchPower: "006001,006011,006015,006023,006035,006040"
    #低压直流配电
    lowDcDistribution: "004003"
    #铅酸电池
    leadAcidBattery: "007005,007012"
    #锂电池
    lithiumBattery: ""
    #普通空调
    commonAir: "015012,015016"
    #机房专用空调
    roomAir: "011087,011088,011093,011094"
    #中央空调末端
    centreAir: "012001,012003,012030,012031,012033"
    #动环监控
    powerMonitor: "076010,076040,076041,076042"
    
provinceId: 01-01