server:
  port: 6161
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: -1


elasticsearch:
  #  nodes: 192.168.172.102:9200            #多个节点用英文逗号分隔,注意这里要用9200端口
  #  index_name: knowledgemanage              #index的名称
  #  type_name: klgtype                  #type的名称
  nodes: 10.1.203.120:9300
  newnodes: 10.1.203.120:9200
  clustername: elasticsearchv
  index_name: knowledgemanage
  type_name: klgtype
  scroll_select_count: 2000
  scroll_select_thread: 4



ftp:
  host: 10.1.203.120
  port: 21
  username: vsftpd
  password: sudoroot#202L

#临时目录设置,linux服务器下请设置成/tmp/,注意要以斜杠结尾
tmp:
  dir: /tmp/


#######################################################################################
mybatis:
  mapper-locations: classpath:sqlmap/*.xml

#深度分析的告警取值
alerttype:    #告警类型
  temalert: '017010'  #温度告警取值
  smokealert: '017002,017003,016010,016011'   #烟感告警取值
  wateralert: '017001'    #漏水、水浸告警取值


# 机房温度分析定时任务采集时间
RoomTemperatureTaskCron: 0 0 2 * * ?

#作业管理定时任务执行时间
workTime: "0 10 1 * * ?"
