local:
  kafka:
    bootstrap_servers: 10.1.4.48:9092,10.1.4.49:9092,10.1.4.50:9092
    producer:
      retries: 0
      batch-size: 5
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: consumer-${ENV_APP_NAME:spider-gemc}
      auto-offset-reset: latest
      enable-auto-commit: false
      auto-commit-interval: 500
      session.timeout.ms: 60000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 3    # 配置partions分区数, 保证每个分区一个消费线程
      ack-mode: manual
    properties:
      session.timeout.ms: 60000

spring:
  kafka: # kafka 配置
    bootstrap-servers: 10.1.4.48:9092,10.1.4.49:9092,10.1.4.50:9092
    producer:
      retries: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: consumer_alert_service
      auto-offset-reset: latest
       # 设置成手工提交(spring代理提交)
      enable-auto-commit: false
      auto-commit-interval: 2000
      session.timeout.ms: 20000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual
      concurrency: 3    # 配置partions分区数, 保证每个分区至少1个消费线程     
    properties:
      session.timeout.ms: 60000



#============== UMS机房 kafka ===================
centerUmsRoom:
  kafka:
    enable: true
    bootstrap-servers: 10.1.4.48:9092,10.1.4.49:9092,10.1.4.50:9092
    producer:
      retries: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      concurrency: 3    # 配置partions分区数, 保证每个分区一个消费线程
