server:
  port: 9101

spring:
  cloud.nacos.discovery:
    ip: 10.12.8.147
    port: 30424
    
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 60000

feign-client:
  ribbon:
    OkToRetryOnAllOperations: true
    MaxAutoRetries: 3


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


energyCabinetColumnDailyReportSchedule.ontime: 0 0 22 * * ?
energyCabinetDailyReportSchedule.ontime: 0 0 22 * * ?
energyCabinetDailyReportSwitch: false
energyCabinetColumnDailyReporSwitch: false
cabinet.es.executor.corePoolSize: 5
cabinet.es.executor.maxPoolSize: 8

aspire.webbas.json.serialization.write.timestamp: true