server:
  port: 9102

spring:
#   cloud.nacos.discovery:
#     ip: 10.12.12.161
#     port: 31573
    
cabinet.es.provinceId: 01-01

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 60000

feign-client:
  ribbon:
    OkToRetryOnAllOperations: true
    MaxAutoRetries: 3


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    org.springframework: info
    com.aspire.spider.m.cabinet: info

ftp:
  host: 10.1.4.113
  port: 21
  username: vsftpd
  password: wccQKPbCmx8@r*6p
  password2: wccQKPbCmx8@r*6p
# fsu.ftp.download.path: "D://tmp//ftp//test//" 
fsu.ftp.update.path: "/upload/binterface/ftpProxy/"
# ftpProxy.download.path: "D://tmp//ftp//ftpProxy1//"


spring.jackson.time-zone: GMT+8