server:
  port: 28015

spring:
  zipkin:
    enabled: false
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0

sample:
  zipkin:
    enabled: false

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: true

#es
elasticsearch:
  index.name: ums-ywjd