server:
  port: 28071
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: -1

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
  http:
    encoding:
      force: true
      charset: UTF-8
      # enabled: true
  messages:
    encoding: UTF-8
  #邮件服务相关配置
  mail:
    host: smtp.qq.com
    username: 666666@qq.com
    password: 12345678
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true

sample:
  zipkin:
    enabled: true

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: info
    # com.mirror.report.finereport: info
    # com.alibaba.druid: debug
    # org.apache.ibatis: debug

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 60000


#excel临时文件存储位置
excel.tmp.file.dir: d:/666/


#报表最大行数限制
reportMaxRow: 200000

mybatis:
  mapperLocations:
    - classpath*:sqlmap/*Mapper.xml
  type-aliases-package:
    org.springboot.sample.entity
  # configuration:
  #   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
